var schedule=require('node-schedule');
var HongKongHorseRace=require('./HongKongHorseRace.js');
var SlovakiaKeno=require('./SlovakiaKeno.js');
var SlovakiaMin=require('./SlovakiaMin.js');
var SlovakiaPC=require('./SlovakiaPC.js');
var anhui115=require('./anhui115.js');
var anhuiQuick3=require('./anhuiQuick3.js');
var HongKonglottery=require('./HongKonglottery.js');
var beijingKeno= require('./beijingKeno.js');
var beijingMin=require('./beijingMin.js');
var beijingPC=require('./beijingPC.js');
var beijingQuick3=require('./beijingQuick3.js');
var beijingRace=require('./beijingRace.js');
var chongqingHappy=require('./chongqingHappy.js');
var chongqingHour=require('./chongqingHour.js');
var fucai3D=require('./fucai3D.js');
var guangdong115=require('./guangdong115.js');
var guangxiQuick3=require('./guangxiQuick3.js');
var hubeiQuick3=require('./hubeiQuick3.js');
var hunanHappy=require('./hunanHappy.js');
var jiangsu115=require('./jiangsu115.js');
var jiangsuQuick3=require('./jiangsuQuick3.js');
var jiangxi115=require('./jiangxi115.js');
var shandong115=require('./shandong115.js');
var shanghai115=require('./shanghai115.js');
var shanghaiHour=require('./shanghaiHour.js');
var shanghaiQuick3=require('./shanghaiQuick3.js');
var taiwan3xingcaiLottery=require('./taiwan3xingcaiLottery.js');
var taiwan4xingcaiLottery=require('./taiwan4xingcaiLottery.js');
var taiwan38leLottery=require('./taiwan38leLottery.js');
var taiwan539Lottery=require('./taiwan539Lottery.js');
var taiwanKeno=require('./taiwanKeno.js');
var taiwanlottoLottery=require('./taiwanlottoLottery.js');
var taiwanMin=require('./taiwanMin.js');
var taiwanPC=require('./taiwanPC.js');
var HongKongRace=require('./HongKongRace.js');
var ticaiP3=require('./ticaiP3.js');
var xinjiangHour=require('./xinjiangHour.js');
var rule=new schedule.RecurrenceRule();
rule.minute=[0,5,10,15,20,25,30,35,40,45,50,55];
var j=schedule.scheduleJob(rule,function(){
anhui115.anhui115();
anhuiQuick3.anhuiQuick3();
beijingKeno.beijingKeno();
beijingMin.beijingMin();
beijingPC.beijingPC();
beijingQuick3.beijingQuick3();
beijingRace.beijingRace();
chongqingHappy.chongqingHappy();
chongqingHour.chongqingHour();
fucai3D.fucai3D();
guangdong115.guangdong115();
guangxiQuick3.guangxiQuick3();
hubeiQuick3.hubeiQuick3();
hunanHappy.hunanHappy();
jiangsu115.jiangsu115();
jiangsuQuick3.jiangsuQuick3();
jiangxi115.jiangxi115();
shandong115.shandong115();
shanghai115.shanghai115();
shanghaiHour.shanghaiHour();
shanghaiQuick3.shanghaiQuick3();
taiwan3xingcaiLottery.taiwan3xingcaiLottery();
taiwan4xingcaiLottery.taiwan4xingcaiLottery();
taiwan38leLottery.taiwan38leLottery();
taiwan539Lottery.taiwan539Lottery();
taiwanKeno.taiwanKeno();
taiwanlottoLottery.taiwanlottoLottery();
taiwanMin.taiwanMin();
taiwanPC.taiwanPC();
ticaiP3.ticaiP3();
xinjiangHour.xinjiangHour();
});
HongKongHorseRace.HongKongHorseRace();
HongKonglottery.HongKonglottery();
HongKongRace.HongKongRace();
SlovakiaKeno.SlovakiaKeno();
SlovakiaMin.SlovakiaMin();
SlovakiaPC.SlovakiaPC();
