var VietnamLottoAJ=require('./VietnamLottoAJ.js');
var VietnamLottoPY=require('./VietnamLottoPY.js');
var VietnamLottoXN=require('./VietnamLottoXN.js');
var VietnamLottoHZMS=require('./VietnamLottoHZMS.js');
var VietnamLottoSH=require('./VietnamLottoSH.js');
var VietnamLottoBL=require('./VietnamLottoBL.js');
var VietnamLottoTN=require('./VietnamLottoTN.js');
var VietnamLottoSZ=require('./VietnamLottoSZ.js');
var VietnamLottoQC=require('./VietnamLottoQC.js');
var VietnamLottoCRandYL=require('./VietnamLottoCRandYL.js');
var VietnamLottoPS=require('./VietnamLottoPS.js');
var VietnamLottoTD=require('./VietnamLottoTD.js');
var VietnamLottoTTandJODH=require('./VietnamLottoTTandJODH.js');
var VietnamLottoDLandQJ=require('./VietnamLottoDLandQJ.js');
var VietnamLottoHJ=require('./VietnamLottoHJ.js');
var VietnamLottoJLandNS=require('./VietnamLottoJLandNS.js');
VietnamLottoJLandNS.VietnamLottoJLandNS();
VietnamLottoHJ.VietnamLottoHJ();
VietnamLottoDLandQJ.VietnamLottoDLandQJ();
VietnamLottoTTandJODH.VietnamLottoTTandJODH();
VietnamLottoTD.VietnamLottoTD();
VietnamLottoPS.VietnamLottoPS();
VietnamLottoAJ.VietnamLottoAJ();
VietnamLottoPY.VietnamLottoPY();
VietnamLottoXN.VietnamLottoXN();
VietnamLottoHZMS.VietnamLottoHZMS();
VietnamLottoSH.VietnamLottoSH();
VietnamLottoBL.VietnamLottoBL();
VietnamLottoTN.VietnamLottoTN();
VietnamLottoSZ.VietnamLottoSZ();
VietnamLottoQC.VietnamLottoQC();
VietnamLottoCRandYL.VietnamLottoCRandYL();
process.on('uncaughtException',function(err){
  console.log(err);
  console.log(err.stack);});
